# TAREA

1.-Leer y realizar los ejemplos del capitulo 1 y 2 de https://jakevdp.github.io/PythonDataScienceHandbook/index.html Hacer un notebook.

## Help and Documentation in IPython
### Accessing Documentation with ?

In [1]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



Because finding help on an object is so common and useful, IPython introduces the '?' character as a shorthand for accessing this documentation and other relevant information

In [2]:
len?

In [3]:
m_1 = [2,1,41,4,2]
m_1?

### Accessing Source Code with ??

In [4]:
def f_1(x,y):
    return x**2 + y**2
f_1??

Using ? and/or ?? gives a powerful and quick interface for finding information about what any Python function or module does.

In [5]:
*Warning?

## IPython Magic Commands

These magic commands are designed to succinctly solve various common problems in standard data analysis.

### Running External Code: %run 

For example, imagine you've created a myscript.py file with some content. You can execute this from your IPython session as follows:

In [6]:
%run myscript.py

1 squared is 1
2 squared is 4
3 squared is 9


Note also that after you've run this script, any functions defined within it are available for use in your IPython session:

In [7]:
my_square(3)

9

### Timing Code Execution: %timeit
which will automatically determine the execution time of the single-line Python statement that follows it. 

In [8]:
%timeit m_1*3

10000000 loops, best of 3: 77.7 ns per loop


In [9]:
 %%timeit
    L = []
    for n in range(1000):
        L.append(n ** 2)

1000 loops, best of 3: 213 µs per loop


## IPython and Shell Commands

IPython bridges this gap, and gives you a syntax for executing shell commands directly from within the IPython terminal. The magic happens with the exclamation point: anything appearing after ! on a line will be executed not by the Python kernel, but by the system command-line.

### Shell Commands in IPython

In [10]:
!ls   # ls = list working directory contents

ejemplos_python.ipynb  myscript.py  Readme.md	   Tarea.md
fun.py		       __pycache__  tarea_1.ipynb


In [11]:
!pwd   # pwd = print working directory

/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana1


In [12]:
!echo "printing from the shell"

printing from the shell


### Passing Values to and from the Shell

In [13]:
contenido = !ls -a
print(contenido)

['.', '..', 'ejemplos_python.ipynb', 'fun.py', '.ipynb_checkpoints', 'myscript.py', '__pycache__', 'Readme.md', 'tarea_1.ipynb', 'Tarea.md']


In [14]:
direccion = !pwd
print(direccion)

['/home/echeveste/Mis_trabajos/analisis_datos/da2019-Oscar2401/Semana1']


In [15]:
type(direccion)

IPython.utils.text.SList

In [16]:
mens = "hola Python"
!echo {mens}

hola Python


## Introduction to NumPy

In [18]:
import numpy as np

### A Python List Is More Than Just a List

In [23]:
my_list = list(range(10))
print(my_list)
print(type(my_list[0]))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'int'>


In [26]:
my_list_2 = [str(n) for n in my_list]
print(my_list_2)
print(type(my_list_2[0]))

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'str'>


In [28]:
my_list_3 = [False, "hola", 3.1416, 32]
[type(item) for item in my_list_3 ]

[bool, str, float, int]

### Fixed-Type Arrays in Python

The built-in array module (available since Python 3.3) can be used to create dense arrays of a uniform type:

In [33]:
import array

In [34]:
A = array.array('i', my_list)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### Creating Arrays from Python Lists

In [36]:
np.array([1,2,3,4,5,6,7,8,9],dtype='float32')

array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [37]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [41]:
import math
np.full((4, 3), math.e)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [43]:
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [44]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [46]:
np.random.random((2,2 ))

array([[0.60534137, 0.65419466],
       [0.11976172, 0.43304222]])

In [49]:
# Create a 2x2 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (2, 2))

array([[-1.36793609, -0.84089241],
       [-0.2069164 ,  0.57432226]])

In [50]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### NumPy Array Attributes

In [56]:
array_r1 = np.random.randint(100, size=10)
array_r2 = np.random.randint(100, size=(5, 5))  
array_r3 = np.random.randint(100, size=(2, 4, 10)) 

In [57]:
print(array_r3.ndim)
print(array_r3.shape)
print(array_r3.size)

3
(2, 4, 10)
80


In [58]:
array_r3.dtype

dtype('int64')

### Array Indexing: Accessing Single Elements